[package]
name = "jsonnlp"
version = "0.0.1"
authors = ["Damir Cavar <damir@semiring.com>"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = { version = "^1.0", default-features = false, features = ["alloc"] }


